@endpoint = http://localhost:8080
@repo = test
###
GET {{endpoint}}/api
Accept: application/json
###
POST {{endpoint}}/api/test
Accept: application/json
###
GET {{endpoint}}/api/test
Accept: application/json
###
GET {{endpoint}}/api/test/tagversion
Accept: application/json
###
GET {{endpoint}}/api/test/lock
Accept: application/json
###
GET {{endpoint}}/api/test/fileversion
Accept: application/json
