version: '3'

services:
  db:
    image: mongo
    restart: unless-stopped

  server:
    image: ghcr.io/dliebg/gum/server:main
    restart: unless-stopped
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
  
  ui:
    image: ghcr.io/dliebg/gum/ui:main
    restart: unless-stopped

  nginx:
    image: ghcr.io/dliebg/gum/nginx:main
    restart: unless-stopped
    ports:
      - 8169:80
      